### ISSUE TITLE
adbGUI 2.0 always crashes

### ISSUE THREAD

**Issue by ghost** [labo89/adbGUI#12]
Hello,

I use adbGUI 2.0
https://github.com/labo89/adbGUI/releases/download/2.0/adbGUI_2.0.zip

But when I run the software, it crashes immediately. Just click on the .exe file and immediately crashed

Tested on a Windows 8.1 (64 bit) + current Windows Update (February 2020)

Can you fix it?

If I use version adbGUI 1.0, no problems.

**Comment by hexadezi** [comment]
Do you have .NET Framework 4.6.1 installed?
https://www.microsoft.com/de-de/download/details.aspx?id=49982

**Comment by ghost** [comment]
> Do you have .NET Framework 4.6.1 installed?
> https://www.microsoft.com/de-de/download/details.aspx?id=49982

Yes.

I currently have .NET Framework 4.8 and in the Windows settings (Windows features) .NET Framework 3.5 (includes .NET 2.0 and 3.0) also enabled.

**Comment by hexadezi** [comment]
Do you get a prompt to install the dependencies? Did you add adb to your path variable?

**Comment by ghost** [comment]
> Do you get a prompt to install the dependencies? 

No.

>Did you add adb to your path variable?

I have downloaded the latest platform tools (29.0.6) and unzipped it on the desktop.

https://dl.google.com/android/repository/platform-tools-latest-windows.zip

Then I put adbGUI.exe into this folder (Desktop\platform-tools_r29.0.6-windows\platform-tools) where the adb.exe file is.

Then I clicked adbGUI.exe and immediately this window with this message appears:

adbGUI has stopped working

A problem caused the program to stop working correctly. Please close the program.

-> Close the program

**Comment by hexadezi** [comment]
Run the adbGUI.exe in an empty folder please.

**Comment by ghost** [comment]
> Run the adbGUI.exe in an empty folder please.

No, that doesn't work either. I created a new folder (empty) on the desktop (Desktop\New Folder) and put the adbGUI.exe in there.

When I run the adbGUI.exe the exact same message appears as before (-> Close the program). 😢

**Comment by hexadezi** [comment]
Do you see something in Event Viewer after the crash?

Event Viewer -> Windows Logs -> Application

**Comment by ghost** [comment]
> 
> 
> Do you see something in Event Viewer after the crash?
> 
> Event Viewer -> Windows Logs -> Application

Only 2 errors.

```
Log Name:      Application
Source:        .NET Runtime
Date:          04/03/2020 13:50:35
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      USB3
Description:
Application: adbGUI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at adbGUI.CheckAndDownloadDependencies.EnvironmentVariableExists()
   at adbGUI.CheckAndDownloadDependencies.Start()
   at adbGUI.Program.Main()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-03-04T12:50:35.000000000Z" />
    <EventRecordID>4821</EventRecordID>
    <Channel>Application</Channel>
    <Computer>USB3</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: adbGUI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at adbGUI.CheckAndDownloadDependencies.EnvironmentVariableExists()
   at adbGUI.CheckAndDownloadDependencies.Start()
   at adbGUI.Program.Main()

</Data>
  </EventData>
</Event>
```

---

```
Log Name:      Application
Source:        Application Error
Date:          04/03/2020 13:50:35
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      USB3
Description:
Faulting application name: adbGUI.exe, version: 1.0.0.0, time stamp: 0x58e67d73
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x011e095e
Faulting process ID: 0x4ec
Faulting application start time: 0x01d5f2237fc7d6cb
Faulting application path: C:\Users\USB3\Desktop\New folder\adbGUI.exe
Faulting module path: unknown
Report ID: bd804e78-5e16-11ea-8260-d43d7e6c07f9
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-03-04T12:50:35.000000000Z" />
    <EventRecordID>4822</EventRecordID>
    <Channel>Application</Channel>
    <Computer>USB3</Computer>
    <Security />
  </System>
  <EventData>
    <Data>adbGUI.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>58e67d73</Data>
    <Data>unknown</Data>
    <Data>0.0.0.0</Data>
    <Data>00000000</Data>
    <Data>c0000005</Data>
    <Data>011e095e</Data>
    <Data>4ec</Data>
    <Data>01d5f2237fc7d6cb</Data>
    <Data>C:\Users\USB3\Desktop\New folder\adbGUI.exe</Data>
    <Data>unknown</Data>
    <Data>bd804e78-5e16-11ea-8260-d43d7e6c07f9</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

**Comment by hexadezi** [comment]
I have removed the check and rebuild the project.

Download it her: https://anonfile.com/d6I219eeo8/adbGUI_wo_CheckAndDownloadDependencies_exe

**Comment by ghost** [comment]
> I have removed the check and rebuild the project.
> 
> Download it her: https://anonfile.com/d6I219eeo8/adbGUI_wo_CheckAndDownloadDependencies_exe

Hello,

it works. Thank you. 😊

Now I see the adbGUI window and my connected Android 9 device.

You can now upload the updated version here on github. It would also be good if you could change the version number to 2.0.0.0, because when I click on the adbGUI.exe file info, it always says 1.0.0.0.

---

Here's some feedbacks.

1. For Phone -> Backup Restore. Can you add multi-select function at "Backup Package" and at "Open file"? Then I can restore my user apps faster.

2. Is this a bug in Phone -> Backup Restore? When I click on "Save to", a Windows Explorer window appears. Choose a save location e.g. Desktop\New folder. And click on "Save". But it does not work. **There is always an error message: backup_03/04/2020_23.36.39.ab
The file name is not valid.** But if I change other file name before e.g. 123. Then it works. 
It would be very good if the file name could be adjusted beforehand (it will be remembered automatically for all further operations). That means if I use "Backup Package", the "ab" file has this filename: NewPipe 0.18.5.ab, OpenBoard 1.3.ab etc.

3. Need multi-select function. Backup of the user application as apk file. Same for install and uninstall function.

4. Is it generally possible without root, but with adbGUI.exe. Backup and restore the game updates of offline games without downloading them again?

**Comment by hexadezi** [comment]
I'm glad it worked for you.

I'm not developing the application right now.

Open a new issue. Maybe I will implement this in the future or someone else will do.
