### ISSUE TITLE
Backup and Restore for Games Updates not possible

### ISSUE THREAD

**Issue by ghost** [labo89/adbGUI#14]
Is it generally possible without root, but with adbGUI.exe. Backup and restore the game updates of offline games without downloading them again?

## System and Software Info

- adbGUI 2.0 
https://anonfile.com/d6I219eeo8/adbGUI_wo_CheckAndDownloadDependencies_exe

- Windows 8.1 (64 Bit)

**Comment by hexadezi** [comment]
If it is possible with cli then it should be possible.
Keep in mind: adb backup is deprecated and may be removed in a future release
