### ISSUE TITLE
file name (preset by the software) cannot be save

### ISSUE THREAD

**Issue by ghost** [labo89/adbGUI#15]
Is this a bug in Phone -> Backup Restore? When I click on "Save to", a Windows Explorer window appears. Choose a save location e.g. Desktop\New folder. And click on "Save". But it does not work. 

There is always an error message: **backup_03/04/2020_23.36.39.ab
The file name is not valid.** 

But if I change other file name before e.g. 123. Then it works.

## System and Software Info

- adbGUI 2.0 
https://anonfile.com/d6I219eeo8/adbGUI_wo_CheckAndDownloadDependencies_exe

- Windows 8.1 (64 Bit)

**Comment by hexadezi** [comment]
fixed
