### ISSUE TITLE
Add file info version to 2.0.0.0

### ISSUE THREAD

**Issue by ghost** [labo89/adbGUI#16]
It would also be good if you could change the version number to 2.0.0.0, because when I click on the adbGUI.exe file info, it always says 1.0.0.0.

## System and Software Info

- adbGUI 2.0 
https://anonfile.com/d6I219eeo8/adbGUI_wo_CheckAndDownloadDependencies_exe

- Windows 8.1 (64 Bit)

**Comment by hexadezi** [comment]
fixed
