### ISSUE TITLE
Add: file name (preset by the software) change the file name assignment method

### ISSUE THREAD

**Issue by ghost** [labo89/adbGUI#17]
It would be very good if the file name could be adjusted beforehand (it will be remembered automatically for all further operations). That means if I use "Backup Package", the "ab" file has this filename: NewPipe 0.18.5.ab, OpenBoard 1.3.ab etc.

## System and Software Info

- adbGUI 2.0 
https://anonfile.com/d6I219eeo8/adbGUI_wo_CheckAndDownloadDependencies_exe

- Windows 8.1 (64 Bit)

**Comment by hexadezi** [comment]
This would involve config file, which I am trying to avoid.
