### ISSUE TITLE
Current version cant stop logcat

### ISSUE THREAD

**Issue by stamepicmorg** [labo89/adbGUI#22]
Current version cant stop logcat. please, look at this PR and commit: https://github.com/labo89/adbGUI/pull/21/commits/6e64089340fbbb0ba1c5e4818a8e04759807231c

**Comment by hexadezi** [comment]
I can stop it. How do you try it?

Did you try this the latest version? https://github.com/labo89/adbGUI/releases/tag/2.2

**Comment by stamepicmorg** [comment]
1st videoproof
[bandicam 2021-05-07 19-13-01-881.zip](https://github.com/labo89/adbGUI/files/6442989/bandicam.2021-05-07.19-13-01-881.zip)

**Comment by stamepicmorg** [comment]
2d videoproof
[bandicam 2021-05-07 19-19-30-782.zip](https://github.com/labo89/adbGUI/files/6443040/bandicam.2021-05-07.19-19-30-782.zip)

**Comment by stamepicmorg** [comment]
3d videoproof
[bandicam 2021-05-07 19-20-32-713.zip](https://github.com/labo89/adbGUI/files/6443042/bandicam.2021-05-07.19-20-32-713.zip)

**Comment by hexadezi** [comment]
If you are using the current version, then you can look in the task manager to see if a child process is created for adbGUI. With Stop this should be terminated. If no child process is created under adbGUI, it cannot be terminated.
 
![Screenshot 2021-05-08 213031](https://user-images.githubusercontent.com/11984646/117551162-a35d5680-b044-11eb-8f42-9203838af0c3.png)

**Comment by stamepicmorg** [comment]
i am using current original version, and installing adb via adb GUI. 

although in pull request in one of commits was fixed it, cause if i compile forked-version - all will be fine.
