### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Cambian** [labo89/adbGUI#4]
I attempted to install your adbGUI about 30 minutes ago and I have NEVER seen my security software flip out that much! Trojan alerts and blocking, firewall attacks and heuristic virus alerts and blocking.

I'll be spending then next couple of days going over my systems. Thanks for wasting my time.

**Comment by hexadezi** [comment]
Hey,
thank you for the information. The hoster was the problem.
I removed the hoster and will add a new one.

Sorry for the inconvenience.
